// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempTest.Infrastructure.Persistence;

#nullable disable

namespace TempTest.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TempTestDbContext))]
    [Migration("20260828144650_AddSprayAndFanEvents")]
    partial class AddSprayAndFanEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TempTest.Domain.FanEvent.FanEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("EndHumidity")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("EndTemperature")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("StartHumidity")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("StartTemperature")
                        .HasColumnType("decimal(9, 2)");

                    b.HasKey("Id");

                    b.ToTable("FanEvents", (string)null);
                });

            modelBuilder.Entity("TempTest.Domain.SensorData.SensorData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("FanOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Humidity")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("ValveOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("SensorData", (string)null);
                });

            modelBuilder.Entity("TempTest.Domain.SprayEvent.SprayEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("EndHumidity")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("EndTemperature")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("StartHumidity")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("StartTemperature")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<decimal>("WaterUsedMilliliters")
                        .HasColumnType("decimal(9, 2)");

                    b.HasKey("Id");

                    b.ToTable("SprayEvents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
